apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>DevOps K8s Stage</title></head>
    <body>
      <h1>Этот файл подгружен через ConfigMap!</h1>
      <p>Я сделал это для понимания архитектуры K8s</p>
    </body>
    </html>
